[build]
  base = "frontend"
  command = "echo 'Skipping build - Redirect only'"
  publish = "public"


# Redirect all traffic to the new Firebase domain
[[redirects]]
  from = "/*"
  to = "https://smaxiso.web.app/:splat"
  status = 301
  force = true