[build]
  base = "frontend"
  command = "npm run build"
  publish = "out"


# Redirect all traffic to the new Firebase domain
[[redirects]]
  from = "/*"
  to = "https://smaxiso.web.app/:splat"
  status = 301
  force = true

